# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pydistrub.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/pydistrub.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protos/pydistrub.proto\x12\x03rpc\"E\n\x0c\x41pplyRequest\x12\x10\n\x08priority\x18\x01 \x01(\x03\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x12\x13\n\x0b\x61llocate_to\x18\x03 \x03(\t\"D\n\rApplyResponse\x12\x1f\n\x07ret_obj\x18\x01 \x01(\x0b\x32\x0e.rpc.RetObject\x12\x12\n\nseesion_id\x18\x02 \x01(\t\"w\n\x07Request\x12\x13\n\x0bremote_func\x18\x01 \x01(\t\x12(\n\x06params\x18\x02 \x03(\x0b\x32\x18.rpc.Request.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x06\n\x04Void\"B\n\tRetObject\x12\x10\n\x08ret_code\x18\x01 \x01(\x03\x12\x0f\n\x07ret_msg\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t2\x91\x01\n\x0cInvokeRemote\x12\x32\n\tTaskApply\x12\x11.rpc.ApplyRequest\x1a\x12.rpc.ApplyResponse\x12.\n\x0eTaskDispatcher\x12\x0c.rpc.Request\x1a\x0e.rpc.RetObject\x12\x1d\n\x05\x43lose\x12\t.rpc.Void\x1a\t.rpc.Voidb\x06proto3'
)




_APPLYREQUEST = _descriptor.Descriptor(
  name='ApplyRequest',
  full_name='rpc.ApplyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='rpc.ApplyRequest.priority', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight', full_name='rpc.ApplyRequest.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allocate_to', full_name='rpc.ApplyRequest.allocate_to', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=100,
)


_APPLYRESPONSE = _descriptor.Descriptor(
  name='ApplyResponse',
  full_name='rpc.ApplyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret_obj', full_name='rpc.ApplyResponse.ret_obj', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seesion_id', full_name='rpc.ApplyResponse.seesion_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=170,
)


_REQUEST_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='rpc.Request.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rpc.Request.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='rpc.Request.ParamsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=291,
)

_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='rpc.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remote_func', full_name='rpc.Request.remote_func', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='rpc.Request.params', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=291,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='rpc.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=299,
)


_RETOBJECT = _descriptor.Descriptor(
  name='RetObject',
  full_name='rpc.RetObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='rpc.RetObject.ret_code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ret_msg', full_name='rpc.RetObject.ret_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='rpc.RetObject.session_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=367,
)

_APPLYRESPONSE.fields_by_name['ret_obj'].message_type = _RETOBJECT
_REQUEST_PARAMSENTRY.containing_type = _REQUEST
_REQUEST.fields_by_name['params'].message_type = _REQUEST_PARAMSENTRY
DESCRIPTOR.message_types_by_name['ApplyRequest'] = _APPLYREQUEST
DESCRIPTOR.message_types_by_name['ApplyResponse'] = _APPLYRESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['RetObject'] = _RETOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ApplyRequest = _reflection.GeneratedProtocolMessageType('ApplyRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLYREQUEST,
  '__module__' : 'protos.pydistrub_pb2'
  # @@protoc_insertion_point(class_scope:rpc.ApplyRequest)
  })
_sym_db.RegisterMessage(ApplyRequest)

ApplyResponse = _reflection.GeneratedProtocolMessageType('ApplyResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPLYRESPONSE,
  '__module__' : 'protos.pydistrub_pb2'
  # @@protoc_insertion_point(class_scope:rpc.ApplyResponse)
  })
_sym_db.RegisterMessage(ApplyResponse)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'ParamsEntry' : _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_PARAMSENTRY,
    '__module__' : 'protos.pydistrub_pb2'
    # @@protoc_insertion_point(class_scope:rpc.Request.ParamsEntry)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'protos.pydistrub_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.ParamsEntry)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'protos.pydistrub_pb2'
  # @@protoc_insertion_point(class_scope:rpc.Void)
  })
_sym_db.RegisterMessage(Void)

RetObject = _reflection.GeneratedProtocolMessageType('RetObject', (_message.Message,), {
  'DESCRIPTOR' : _RETOBJECT,
  '__module__' : 'protos.pydistrub_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RetObject)
  })
_sym_db.RegisterMessage(RetObject)


_REQUEST_PARAMSENTRY._options = None

_INVOKEREMOTE = _descriptor.ServiceDescriptor(
  name='InvokeRemote',
  full_name='rpc.InvokeRemote',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=370,
  serialized_end=515,
  methods=[
  _descriptor.MethodDescriptor(
    name='TaskApply',
    full_name='rpc.InvokeRemote.TaskApply',
    index=0,
    containing_service=None,
    input_type=_APPLYREQUEST,
    output_type=_APPLYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TaskDispatcher',
    full_name='rpc.InvokeRemote.TaskDispatcher',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RETOBJECT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Close',
    full_name='rpc.InvokeRemote.Close',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INVOKEREMOTE)

DESCRIPTOR.services_by_name['InvokeRemote'] = _INVOKEREMOTE

# @@protoc_insertion_point(module_scope)
